services:
  backend:
    build:
      context: backend
    container_name: gig-backend
    ports:
      - "11435:11435"
    environment:
      - TZ=Asia/Tokyo
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:0.4.1
    container_name: gig-ollama
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - type: bind
        source: .ollama
        target: /root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
