services:
  faster-whisper-server:
    build: .
    container_name: faster-whisper
    ports:
      - "8088:8000"
    volumes:
      - faster_whisper:/models
    command: uvicorn src.server:app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
      image: ollama/ollama
      container_name: ollama
      volumes:
        - ollama:/root/.ollama
      ports:
        - "11434:11434"
      restart: unless-stopped
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - "WEBUI_AUTH=false"
    ports:
      - "3033:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  faster_whisper:
  ollama:
  open-webui:
