[project]
name = "gig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.0",
    "faster-whisper>=1.0.3",
    "requests>=2.32.3",
    "torch>=2.4.1",
    "transformers>=4.45.1",
]
